
-- Consultas para verificar datos


USE CINEMA;

-- Ver contenido completo de cada tabla

SELECT * FROM USUARIO;
SELECT * FROM BENEFICIO;
SELECT * FROM SALA;
SELECT * FROM ESTADO_FUNCION;
SELECT * FROM PELICULA;
SELECT * FROM ETIQUETA;
SELECT * FROM COMPRA;
SELECT * FROM FUNCION;
SELECT * FROM BUTACA;
SELECT * FROM PELICULA_ETIQUETA;
SELECT * FROM COMPRA_FUNCION;
SELECT * FROM USUARIO_BENEFICIO;

-- Contar registros de cada tabla por separado

SELECT COUNT(*) AS registros_USUARIO FROM USUARIO;
SELECT COUNT(*) AS registros_BENEFICIO FROM BENEFICIO;
SELECT COUNT(*) AS registros_SALA FROM SALA;
SELECT COUNT(*) AS registros_ESTADO_FUNCION FROM ESTADO_FUNCION;
SELECT COUNT(*) AS registros_PELICULA FROM PELICULA;
SELECT COUNT(*) AS registros_ETIQUETA FROM ETIQUETA;
SELECT COUNT(*) AS registros_COMPRA FROM COMPRA;
SELECT COUNT(*) AS registros_FUNCION FROM FUNCION;
SELECT COUNT(*) AS registros_BUTACA FROM BUTACA;
SELECT COUNT(*) AS registros_PELICULA_ETIQUETA FROM PELICULA_ETIQUETA;
SELECT COUNT(*) AS registros_COMPRA_FUNCION FROM COMPRA_FUNCION;
SELECT COUNT(*) AS registros_USUARIO_BENEFICIO FROM USUARIO_BENEFICIO;

